packages:
  - 'packages/*'

catalogs:
  effect:
    "@effect/docgen": "^0.5.2"
    "@effect/eslint-plugin": "^0.3.2"
    "@effect/language-service": "^0.55.2"
    "@effect/vitest": "^0.27.0"
    "@effect/cli": "^0.72.1"
    "@effect/platform": "^0.93.0"
    "@effect/platform-node": "^0.100.0"
    "effect": "^3.19.3"
