"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PingCli = exports.PingCommand = void 0;
const cli_1 = require("@effect/cli");
const effect_1 = require("effect");
const index_js_1 = require("./Commands/PingOne/index.js");
const RunJSTests_js_1 = require("./Commands/RunJSTests.js");
const RunPublish_js_1 = require("./Commands/RunPublish.js");
const subcommands = effect_1.Array.make(RunJSTests_js_1.runJSTests, RunPublish_js_1.RunPublish, index_js_1.p1Command);
exports.PingCommand = cli_1.Command.make("pingid");
exports.PingCli = exports.PingCommand.pipe(cli_1.Command.withSubcommands(subcommands)).pipe(cli_1.Command.run({ name: "Ping SDK CLI", version: "0.0.1" }));
